sudo: required
services:
  - docker

before_install:
  - docker build -t bluesaluman/docker-react -f Dockerfile.dev .

script:
  - docker run bluesaluman/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-758347747125"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrect_access_key:
    secure: "$AWS_SECRET_KEY"

